server:
  port: 8761
  host: 127.0.0.1
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
#    registerWithEureka: false
#    fetchRegistry: false
spring:
  application:
    name: eureka-server


