
spring:
  application:
    name: product-ms
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/EKART_PRODUCT?useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  servlet:
    context-path: /Ekart
  error:
    whitelabel:
      enables: false
  host: localhost
  port: 3334

logging:
  level:
    org:
      hibernate:
        type: info

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false