spring:
  application:
    name: customer-ms
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/EKART_CUSTOMER?useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true





logging:
  level:
    org:
      hibernate:
        type: info



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka