spring:
  application:
    name: customer-ms
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/EKART_CUSTOMER?useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true



server:
  servlet:
    context-path: /Ekart
  error:
    whitelabel:
      enables: true
  host: localhost
  port: 3336



logging:
  level:
    org:
      hibernate:
        type: info


eureka:
  instance:
    hostname: localhost
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


url:
  product-api:
    product: http://localhost:9000/product-ms/Ekart/product-api/product/
    update: http://localhost:9000/product-ms/Ekart/product-api/update/
  customercart-api:
    products: http://localhost:9000/cart-ms/Ekart/customercart-api/products
    customer: http://localhost:9000/cart-ms/Ekart/customercart-api/customer/

